### ISSUE TITLE
404 links hubstaff and toggl

### ISSUE THREAD

**Issue by muescha** [tiagofsanchez/wfh-tools#3]
on: https://crushingwfh.com/time-tracking/hubstaff/
404 link: https://crushingwfh.com/time-tracking/hubstaff/Hubstaff.com

on https://crushingwfh.com/time-tracking/toggl/
404 link: https://crushingwfh.com/time-tracking/toggl/toggl.com

**Comment by muescha** [comment]
i guess a missing https:// in airtable

**Comment by tiagofsanchez** [comment]
Hi @muescha , my `/utils/api.js` is pointing to my Airtable base that is holding all the data that is why this is having that response. Not necessarily and error or bug, but at your end you will need to set up an airtable database for this to work. 

Also, since I am using `.env` to hold my api keys to Airtable you will have to do the same at your end. 

Hope this helps.

**Comment by muescha** [comment]
yes its not a code error - but your data in your airtable has wrong data. resulting in a 404 error on your production website.

since data is in your airtable i cannot suggest a PR to fix your data (from `Hubstaff.com` to `https://Hubstaff.com`) in the airtable

**Comment by tiagofsanchez** [comment]
Thank you very much @muescha! Yes, I now understand what the problem is - in my airtable I have toggl.com instead of https://toggl.com/ and the href is not the correct one. 
Fixing this right now. 
Again, thank you :)

**Comment by muescha** [comment]
👍

PS: toggle is now ok. But Now hubstuff ia also pointing to toggle

**Comment by tiagofsanchez** [comment]
Was to fast clicking triggering deploy on netlify. Rebuilding again! Thank
you 🙏
